from hardware.panels import *; from hardware.parts import *
# ---
class Controller:
    verbose = True
    profile = None# If set, represents the time series for the power generated by the panels

    # ---
    def __init__(self, env=None, sun = None, battery = None, monitor = None):
        self.sun        = sun
        self.battery    = battery
        self.env        = env
        self.monitor    = monitor
        self.panels     = []
        self.devices    = {}
        self.power      = None # this is calculated later

    ### PANELS SECTION ###
    def add_panel(self, panel):
        panel.set_condition(self.sun.condition)
        self.panels.append(panel)

    ### DEVICES SECTION ###
    def add_device(self, device):
        self.devices[device.name]=device

    def set_device_state(self, name, state):
        self.devices[name].state = state

    ###
    def add_all_panels(self):
        self.add_panel(EPanel(self.sun, 'E'))
        self.add_panel(WPanel(self.sun, 'W'))
        self.add_panel(TPanel(self.sun, 'T'))
    ###
    def get_panel(self, name):
        for p in self.panels:
            if p.name==name: return p
        return None
    ###
    def panels_info(self):
        info = f'''Number of panels: {len(self.panels)}\n'''
        for p in self.panels:
            info += f'''Panel info: {p.info()}\n'''
        print(info)

    
    ###
    # An aggregator, to collect power from the panels
    def calculate_power(self):
        power = None
        for p in self.panels:
            if power is None:
                power = p.power()
            else:
                power = power + p.power()

        self.power = power

    ### Static method to read the panel exposure profile
    @staticmethod
    def read_profile(filename):
        try:
            with open(filename, 'rb') as f: Controller.profile = np.load(f)
            if Controller.verbose: print(f'''Loaded data from file "{filename}", number of points: {Controller.profile.size}''')
        except:
            if Controller.verbose: print(f'''ERROR using file {filename} as the data source for the power profile''')

    ######### Simulation code
    def run(self):
    
        ### SimPy machinery: print(f'''Clock: {self.sun.mjd[myT]}, power: {Panel.profile[myT]}''')
    
        while True:
            myT     = int(self.env.now)
            myPwr   = self.power[myT]
            clock   = self.sun.mjd[myT]

            self.monitor.buffer[myT] = myPwr
            try:
                self.battery.put(myPwr)
            except:
                pass

            for k in self.devices.keys():
                the_device = self.devices[k]
                if clock >60720.0: the_device.state = 'OFF'
                cur = the_device.current()
                if cur>0.0: self.battery.get(cur)

            self.monitor.charge+=myPwr
            self.monitor.battery[myT] = self.battery.level
            
            yield self.env.timeout(1)

    # ------------------------------------------------------------------------------------------------
    ### Unused for now
    # def set_time(self, time):
    #    self.time = time

    ###
    # Refactored to the "add panel", hence deprecated
    #def set_condition(self, condition_list):
    #    for p in self.panels:
    #        p.set_condition(condition_list)