1:
  start:  60726.0 # first full day, start
  mode:   charge

2:
  start:  60740.0 # 2970 - sunset
  mode:   powersave

3:
  start:  60756.0 # approx 4391
  mode:   charge

4:
  start:  60770.0 # approx 5804 - sunset
  mode:   science

5:
  start:  60785.0 # approx 7228 - day
  mode:   charge

6:
  start:  60800.0 # 8634 - sunset
  mode:   powersave
