1:
  start:  60726.0 # 1549 - first full day, start
  mode:   charge

2:
  start:  60740.0 # 2970 - sunset
  mode:   powersave

3:
  start:  60756.0 # 4391 - day
  mode:   charge

4:
  start:  60770.0 # 5804 - sunset
  mode:   science

5:
  start:  60785.0 # 7228 - day
  mode:   charge

6:
  start:  60800.0 # 8634 - sunset
  mode:   powersave

7:
  start:  60815.0 # 10061 - day
  mode:   comms

8:
  start:  60829.0 # 11463 - sunset
  mode:   powersave