# This is a generic test input for the simulation

period:
  #start: "2025-02-04 00:00:00" # "2025-02-10 00:00:00"
  #end:   "2025-08-07 23:45:00" # "2025-02-11 23:45:00"
  start: "2026-01-10 20:00:00" # "2025-02-10 00:00:00"
  end:   "2027-01-15 02:00:00" # "2025-02-11 23:45:00"
  deltaT: 900

location:
    latitude:                     -23.814 # degrees
    longitude:                    182.258 # degrees
    height:                       0 # meters

satellites:
  lpf:
    semi_major_km:                5738
    eccentricity:                 0.56489
    inclination_deg:              57.097
    raan_deg:                     0
    argument_of_pericenter_deg:   72.625
    aposelene_ref_time:           '2024-05-01T00:00:00'

  bge:
    semi_major_km:                5738
    eccentricity:                 0.56489
    inclination_deg:              57.097
    raan_deg:                     0
    argument_of_pericenter_deg:   252.625
    aposelene_ref_time:           '2024-05-01T00:00:00'
