solar_panels:  
  config:    
    lander: 0.0 0.0 0.0 # roll, pitch, yaw
    surface_temperature_table: reference/lunarTemperature30degDiviner.txt ## currently ignored!!
    PV_efficiency:
      temp: -173.15 20.0  126.85
      power: 0.356414 0.304828 0.257931
  
  panels:
    EPanel:
      normal:     1 0 0 
      efficiency: 1.0
      area:       0.1565
  
    WPanel:
      normal:     -1 0 0 
      efficiency: 1.0
      area:       0.1565
  
    TPanel:
      normal:     0 0 1
      efficiency: 1.0
      area:       0.313
# ---
battery:
  initial:        3000
  capacity:       6840
  fiducial_voltage:     28 
  charge_efficiency:    0.95
  discharge_efficiency: 0.95

# ---
ssd:
  initial: 0 
  capacity: 32e6

# ---
# Power consumption in Watts
power_consumers:
  preamp: 
    'ON':       0.9
  spectrometer:
    'ANALOG':   1.4
    'ON':       8.0
    'SCIENCE':  11.5
  DCB:
    'ON':       2.0
  UT:
    'ON':       5.3
    'TX':       19
  PDU: 
    'ON':       0.9
  PCDU:
    'HIBER':    0.8
    'ON':       1.5
  PFPS:
    # what the line below does is sum powers of devices in the
    # third item, multiplies by second item and adds the first item 
    'ON':       CUSTOM, 1.0, 0.45, preamp+spectrometer+DCB
  
# Data consumption (bandwidth) in kB/s
ssd_consumers:
  spectrometer:
    'ON':       0.0
    'SCIENCE':  5.0
  DCB:
    'ON':       0.1
  UT:
    'ON':       0.0
    'TX':   -20.0   

