thermal:
  altitude:   0 10 30 70
  power: 0 10 20 30 40
  ## this array should have N_alt rows of N_power values in C
  temperature: [ -10 2  5 10 20,
                  0  10 20 30 40,
                  10 20 30 40 50,
                  20 30 40 60 70]
  tau: 18000 # time constant in seconds
  Tstart: 10

solar_panels:  
  config:    
    lander: 0.0 0.0 0.0 # roll, pitch, yaw
    panel_temperature_table: reference/lunarTemperature30degDiviner.txt ## currently ignored!!
    efficiency_all: 0.9  # applied to any final power
    PV_efficiency:
      temp: -173.15 20.0  126.85
      power: 0.356414 0.304828 0.257931
  
  panels:
    EPanel:
      normal:     1 0 0 
      efficiency: 1.0
      area:       0.1565
  
    WPanel:
      normal:     -1 0 0 
      efficiency: 1.0
      area:       0.1565
  
    TPanel:
      normal:     0 0 1
      efficiency: 1.0
      area:       0.313
# ---
battery:
  # Units are defined here as well and are required
  initial:        120.0
  capacity:       240.99
  charge_unit:    Ah

  capacity_fade: 0.0063  # capacity fade applied to capacity
  self_discharge: 0.01 # defined as fractional loss over 28 days
  VOC_table: ../data/hardware/battery/battery_VOC.dat
  # meaning of columns in the look-up table.
  # SOC = State of charge
  # VOC@T = open circuit voltage at temperature T
  # R@T = internal resistance at temperature T
  VOC_table_cols: SOC VOC@0 R@0 VOC@20 R@20 VOC@40 R@40

# ---
ssd:
  initial: 0 
  capacity: 32e6

# ---
# Power consumption in Watts
power_consumers:
  preamp: 
    'ON':       0.9
  spectrometer:
    'ANALOG':   1.4
    'ON':       8.0
    'SCIENCE':  11.5
  DCB:
    'ON':       2.0
  UT:
    'ON':       5.3
    'TX':       19
  PDU: 
    'ON':       0.9
  PCDU:
    'HIBER':    0.8
    'ON':       1.5
  PFPS:
    # what the line below does is sum powers of devices in the
    # third item, multiplies by second item and adds the first item 
    'ON':       CUSTOM, 1.0, 0.45, preamp+spectrometer+DCB
  HEATER:
    'ON':       1.0
  
# ---
# this defines how much heat is dissipated outside, so
# that we can subtracting when measuring heat contributions inside
# heat not accounted here is assumed to be dissipated inside

outside_heat:
  preamp:
    'ON':       0.9
  UT:
    'TX':       4
  
# Data consumption (bandwidth) in kB/s
ssd_consumers:
  spectrometer:
    'ON':       0.0
    'SCIENCE':  5.0
  DCB:
    'ON':       0.1
  UT:
    'ON':       0.0
    'TX':   -20.0   

