solar_panels:  
  config:    
    lander_pitch: 0.0
    lander_roll: 0.0
    lander_yaw: 0.0    
    surface_temperature_table: reference/lunarTemperature30degDiviner.txt
    PV_efficiency:
      temp: -173.15 20.0  126.85
      power: 0.356414 0.304828 0.257931
    
    
  EPanel:
    normal: 1 0 0 
    efficiency: 1.0
    area: 0.1565
  
  WPanel:
    normal: -1 0 0 
    efficiency: 1.0
    area: 0.1565
  
  TPanel:
    normal: 0 0 1
    efficiency: 1.0
    area: .313

battery:
  initial: 120.0 #in Ah
  capacity: 240.99 #in Ah
  capacity_fade: 0.0063  # capacity faed applied to capacity
  R_internal: 2 # in Ohms, gives ~5% in power loss for a 20W load at 29V
  self_discharge: 0.03 # defined as fractional loss over 28 days
  VOC_table: ../hardware_data/battery/battery_VOC.dat
  # meaning of columns in the look-up table.
  # SOC = State of charge
  # C@T = charge voltage at temperature T
  # D@T = discharge voltage at temperature T
  VOC_table_cols: SOC C@0 D@0 C@20 D@20 C@40 D@40

 
ssd:
  initial: 0 
  capacity: 32e6


# consumption in Watts
power_consumers:
  spectrometer:
    'OFF':      0.0
    'ON':       10
    'SCIENCE':  12
  comms:
    'OFF':      0.0
    'ON':       0.1
    'TX':       19
  bms:
    'OFF':      0.0
    'ON':       1.0
  pfps:
    'OFF':      0.0
    'ON':       6.1   # 6 + 0.1 PDU
  dcb:
    'OFF':      0.0
    'ON':       2.0

# consumption in kB/s
ssd_consumers:
  spectrometer:
    'OFF':      0.0
    'ON':       5.0

  dcb:
    'OFF':      0.0
    'ON':       0.1
  
  comms:
    'OFF':      0.0
    'ON':       0.0
    'TX':   -20.0   

