# Description of the available modes of the hardware components
science:
  spectrometer: SCIENCE
  comms: OFF
  bms: OFF
  controller: SCIENCE
charge:
  spectrometer: OFF
  comms: OFF
  bms: ON
  controller: CHARGE