# Map of the available LuSEE modes to the states of its hardware components
science:
  preamp:       'ON'
  spectrometer: 'SCIENCE'
  UT:           'OFF'
  PDU:          'ON'
  PCDU:         'HIBER'
  PFPS:         'ON'
  DCB:          'ON'

maint:
  preamp:       'ON'
  spectrometer: 'OFF'
  UT:           'ON'
  PDU:          'ON'
  PCDU:         'ON'
  PFPS:         'ON'
  DCB:          'ON'

powersave:
  preamp:       'ON'
  spectrometer: 'OFF'
  UT:           'OFF'
  PDU:          'ON'
  PCDU:         'HIBER'
  PFPS:         'ON'
  DCB:          'ON'
  