# Map of the available LuSEE modes to the states of its hardware components
science:
  spectrometer: 'SCIENCE'
  comms: 'OFF'
  bms: 'OFF'
  controller: 'ON'
charge:
  spectrometer: 'OFF'
  comms: 'OFF'
  bms: 'ON'
  controller: 'ON'
comms:
  spectrometer: 'OFF'
  comms: 'ON'
  bms: 'ON'
  controller: 'ON'
powersave:
  spectrometer: 'OFF'
  comms: 'OFF'
  bms: 'OFF'
  controller: 'ON'
  