name: opsim-test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ maxim-ci ]
  pull_request:
    branches: [ maxim-ci ]

  # Enable manual activation, too
  workflow_dispatch:
jobs:
  luseepy-test:
    runs-on: ubuntu-latest
    env:
       PYTHONPATH: .:..
       LUSEE_DRIVE_DIR: Drive
       LUSEE_OUTPUT_DIR: ./output
    container: lusee/lusee-night-unity-luseepy:1.2
    steps:
      - uses: actions/checkout@v4
      - run: echo 'opsim CI'

