name: opsim-test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ maxim-ci ]
  pull_request:
    branches: [ maxim-ci ]

  # Enable manual activation, too
  workflow_dispatch:
jobs:
  luseepy-test:
    runs-on: ubuntu-latest
    env:
       PYTHONPATH: .:..
       LUSEE_DRIVE_DIR: Drive
       LUSEE_OUTPUT_DIR: ./output
    container: lusee/lusee-night-unity-luseepy:1.2
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo '*** opsim CI ***'
          pwd
          ls -l
          echo pythonpath: $PYTHONPATH
          export LUSEEPY_PATH=/user/luseepy
          export LUSEEOPSIM_PATH=`pwd`
          echo '*** Scanning env for LUSEE items:'
          env | grep LUS
          echo *** End scan, proceed to list /user
          ls -l /user
          echo '**************************'
          python -c 'import sys; print(sys.path)'
# ./test/battery_discharge_test.py -v




